[[redirects]]
    from = "/favicon.ico"
    to = "https://visuallysynced.xyz/favicon.ico"
    status = 200
    force = true
    
[[redirects]]
    from = "/git/*"
    to = "https://visuallysynced.xyz/gh/thumbsup/:splat"
    status = 301
    force = true
